//
// Created by mariocaster on 2/27/16.
//

#ifndef CPPDESIGNPATTERNS_CLASSDECORATOREXAMPLE_H
#define CPPDESIGNPATTERNS_CLASSDECORATOREXAMPLE_H


class ClassDecoratorExample {

};


#endif //CPPDESIGNPATTERNS_CLASSDECORATOREXAMPLE_H
