//
// Created by mariocaster on 2/27/16.
//

#ifndef CPPDESIGNPATTERNS_OPTIONSDECORATOR_H
#define CPPDESIGNPATTERNS_OPTIONSDECORATOR_H


class OptionsDecorator {

};


#endif //CPPDESIGNPATTERNS_OPTIONSDECORATOR_H
